# Generated by Django 5.1.7 on 2025-03-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('in_progress', 'In Progress'), ('pending', 'Pending'), ('on the way', 'On The Way'), ('delivered', 'Delivered')], default='pending', max_length=255),
        ),
    ]
