# Generated by Django 5.1.7 on 2025-03-16 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('on the way', 'On The Way'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered')], default='pending', max_length=255),
        ),
    ]
